# Generated by Django 5.2.3 on 2025-07-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
