# Generated by Django 5.2.3 on 2025-07-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_alter_leaverequest_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-start_date']},
        ),
    ]
