# Generated by Django 5.2.3 on 2025-07-08 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0009_alter_leaverequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('annual', 'Annual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave')], default='Casual Leave', help_text='Type of leave being requested.', max_length=50),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the leave request was submitted.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(help_text='The employee submitting this leave request.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='emp_app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(help_text='Reason for the leave request.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Current status of the leave request.', max_length=20),
        ),
    ]
