# Generated by Django 5.2.3 on 2025-07-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0010_leaverequest_leave_type_leaverequest_requested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='reason',
        ),
    ]
